[workspace]
authors = ["Mike Smyth <Mike.M.Smyth@jpl.nasa.gov>"]
channels = ["conda-forge", "fake-afids-conda-channel"]
name = "build-pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
geocal = "*"
afids-development-tools = "*"
afids = "*"
conda = "*"
#tensorflow = "*"
scikit-learn = "*"
loguru = "*"
loguru-config = "*"
pytest-loguru = "*"
gdb = "*"
mypy = "*"
pandas-stubs = "*"
# Useful, not strictly necessary
pandasql = "*"
git-annex = "*"
# Swig 4.4.0 just came out, and doesn't seem to work. We'll fix this
# at some point, for for now restrict ourselves to the older version of swig
swig = "<4.4.0"

[pypi-dependencies]
# There isn't  currently a conda-forge package for the
# python 3.13 verions we are using. So for now, grab the
# pip package. Can change to conda-forge when it is available.
tensorflow = "*"
